---
abstract: ~
author:
  - 'Atsushi Nagase <ngs@cpan.org>'
build_requires:
  DBIx::Class::Schema::Versioned: 0
  ExtUtils::MakeMaker: 6.42
  FindBin::libs: 0
  Test::More: 0
  Test::mysqld: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Storage-DBI-mysql-backup
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  DBIx::Class::Storage::DBI::mysql: 0
  FindBin::libs: 0
  MySQL::Backup: 0
  Symbol: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ngs/p5-dbix-class-storage-dbi-mysql-backup
version: 0.03
